# Generated by Django 5.1.3 on 2024-11-26 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Objeto', '0002_generos'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='generos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='genero', to='Objeto.generos'),
            preserve_default=False,
        ),
    ]
