# Generated by Django 5.1.3 on 2024-11-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Objeto', '0003_producto_generos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generos',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
