# Generated by Django 5.1.3 on 2024-11-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Objeto', '0005_rename_generos_generos_nombre_remove_producto_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
